### ISSUE TITLE
Add Support for Worker Metrics and Queue Counts

### ISSUE THREAD

**Issue by salman-ahmad** [jenniferplusplus/opentelemetry-instrumentation-bullmq#6]
hey all,

Thank you for making this package :)!!

We have a use case for tracking performance of each worker and each queue's job counts. We would like to scale up/down our instances using queue depth and/or performance of workers.

Would it be possible to add support for these?

Bullmq has [metrics](https://docs.bullmq.io/guide/metrics) option that could be enabled on a worker. They also have a function `queue..getJobCounts()`. I am not sure how easy or hard it would be to integrate these. I am not very familiar with opentelemetry instrumentation otherwise I would push a PR

Thank you for your help!

**Comment by jenniferplusplus** [comment]
I was just thinking about this kind of thing, actually. OTel JS says the metrics API is stable, so this is probably doable. But I'm not familiar with other auto-instrumentations that included metrics, so I'm not 100% sure how I would go about doing this.

**Comment by jenniferplusplus** [comment]
I don't plan to spend any active development time on this project in the near future, so I'm going to close out this issue. If you're still looking for bullmq metrics, this project was mentioned recently, and it seems like a good option.
https://github.com/UpHabit/bull_exporter
