### ISSUE TITLE
Support for bullmq 4.x

### ISSUE THREAD

**Issue by Pho3niX90** [jenniferplusplus/opentelemetry-instrumentation-bullmq#9]

**Comment by jenniferplusplus** [comment]
Hi @Pho3niX90! I don't actually use BullMQ anymore. I'm no longer part of the project that prompted me to create this library. I may be able to get to this in the near future, but I can't guarantee it. I'm more than happy to review a PR if you can implement it before I do.

**Comment by jenniferplusplus** [comment]
And fwiw, I asked the BullMQ team if they want to take it over. That's probably the ideal scenario, if they're interested. You can follow that discussion here:

https://github.com/taskforcesh/bullmq/issues/2048
